"""weights (int => float)

Revision ID: 45b081e2514c
Revises: 5cf14bfdaa5b
Create Date: 2023-07-14 20:52:39.877049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b081e2514c'
down_revision = '5cf14bfdaa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Card_table', schema=None) as batch_op:
        batch_op.alter_column('weights',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Card_table', schema=None) as batch_op:
        batch_op.alter_column('weights',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
