"""field length extension

Revision ID: 5cf14bfdaa5b
Revises: 71201d36f2f9
Create Date: 2023-07-13 21:48:50.371376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf14bfdaa5b'
down_revision = '71201d36f2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Card_table', schema=None) as batch_op:
        batch_op.alter_column('side_2',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=2048),
               existing_nullable=False)

    with op.batch_alter_table('deck_table', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_table', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('Card_table', schema=None) as batch_op:
        batch_op.alter_column('side_2',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
