"""add next_repetition in card model

Revision ID: 5da87a6cab4a
Revises: 45b081e2514c
Create Date: 2023-07-14 23:01:11.519615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da87a6cab4a'
down_revision = '45b081e2514c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Card_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_repetition', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Card_table', schema=None) as batch_op:
        batch_op.drop_column('next_repetition')

    # ### end Alembic commands ###
